// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using simple_crud.Db;

#nullable disable

namespace simple_crud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240428142551_Add-ImagePath")]
    partial class AddImagePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("simple_crud.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8052),
                            ImagePath = "",
                            Name = "Basic of Physics",
                            Price = 100,
                            UpdatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8053)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8056),
                            ImagePath = "",
                            Name = "Chemistry of Nature",
                            Price = 200,
                            UpdatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8057)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8059),
                            ImagePath = "",
                            Name = "Computer Programming",
                            Price = 300,
                            UpdatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8060)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8063),
                            ImagePath = "",
                            Name = "Mathematics",
                            Price = 150,
                            UpdatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8063)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8066),
                            ImagePath = "",
                            Name = "Physics of Nature",
                            Price = 250,
                            UpdatedAt = new DateTime(2024, 4, 28, 14, 25, 50, 945, DateTimeKind.Utc).AddTicks(8066)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
