// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using simple_crud.Db;

#nullable disable

namespace simple_crud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240428123800_Add-Image")]
    partial class AddImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("simple_crud.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6094),
                            Name = "Basic of Physics",
                            Price = 100,
                            UpdatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6095)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6098),
                            Name = "Chemistry of Nature",
                            Price = 200,
                            UpdatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6099)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6102),
                            Name = "Computer Programming",
                            Price = 300,
                            UpdatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6102)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6105),
                            Name = "Mathematics",
                            Price = 150,
                            UpdatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6106)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6109),
                            Name = "Physics of Nature",
                            Price = 250,
                            UpdatedAt = new DateTime(2024, 4, 28, 12, 37, 59, 127, DateTimeKind.Utc).AddTicks(6109)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
